sudo: required
before_install:
  - sudo apt-get install ant
  - sudo apt-get install tclsh
  - sudo apt install default-jre
  
# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc
  
install:

# Build steps
script:
  - make
