sudo: required

# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - gcc
  
matrix:
  fast_finish: true
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - sudo apt-get install ant
    - sudo apt-get install tclsh
    - sudo apt install default-jre
    - sudo apt-get install swig
    - sudo apt-get install google-perftools
    - sudo apt-get install libgoogle-perftools-dev
    - sudo apt-get install python3 python3-dev
    - eval "${MATRIX_EVAL}"
    - git submodule update --init --recursive

install:

# Build steps
script:
  - sed -i 's/nestingLimit = 64/nestingLimit = 1024/g' third_party/UHDM/third_party/capnproto/c++/src/capnp/message.h
  - sed -i 's/8 \* 1024 \* 1024/64 \* 1024 \* 1024 \* 1024 - 1/g' third_party/UHDM/third_party/capnproto/c++/src/capnp/message.h
  - make release
  - sudo make install
  - make test_install
  - make test

