sudo: required
before_install:
  - sudo apt-get install ant
  - sudo apt-get install tclsh
  - sudo apt install default-jre
  
# Enable C++ support
language: cpp


matrix: 
   - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

# Compiler selection
compiler:
  - gcc
  
install:

# Build steps
script:
  - make
