sudo: required

# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - gcc
  
matrix:
  fast_finish: true
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

before_install:
    - sudo apt-get install ant
    - sudo apt-get install tclsh
    - sudo apt install default-jre
    - sudo apt-get install swig
    - sudo apt-get install google-perftools
    - sudo apt-get install libgoogle-perftools-dev
    - eval "${MATRIX_EVAL}"


install:

# Build steps
script:
  - make
